### ISSUE TITLE
CRAN release checklist

### ISSUE THREAD

**Issue by richfitz** [reconhub/distcrete#15]
- [x] increase version to 1.0.0
- [x] update repo status to "active"
- [x] add CRAN badge to README
- [x] add CRAN installation instructions to README
- [x] generate pkgdown website to replace old staticdocs one
- [x] test on r-release (rhub)
- [x] test on r-devel (rhub)
- [x] update maintainer field

**Comment by stephlocke** [comment]
All of the above done. pkgdown generation code currently on the pkgdown branch. https://github.com/reconhub/distcrete/tree/pkgdown

I don't typically use makefiles so @richfitz i'd appreciate it if you could make sure I didn't bork the file.

**Comment by richfitz** [comment]
Sure; will check tomorrow morning. Thanks @stephlocke!

**Comment by richfitz** [comment]
Remaining pkgdown bits to #17
